src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * Users
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @UniqueEntity("email")
 * @UniqueEntity("pseudo")
 */
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="pseudo", type="string", length=50, nullable=false, unique=true)
     */
    private $pseudo;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100, nullable=false, unique=true)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password_hash", type="string", length=150, nullable=false)
     */
    private $passwordHash;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $roles;


    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }


    /**
     * Returns the identifier for this user (e.g. its username or email address).
     */
    public function getUserIdentifier(): string
    {
        return $this->pseudo;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->pseudo;
    }

    public function setUsername(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->passwordHash;
    }

    public function setPassword(string $passwordHash): self
    {
        $this->passwordHash = $passwordHash;

        return $this;
    }

    public function getPasswordHash(): ?string
    {
        return $this->passwordHash;
    }

    public function setPasswordHash(string $passwordHash): self
    {
        $this->passwordHash = $passwordHash;

        return $this;
    }


}

src/Controller/RegisterController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class RegisterController extends AbstractController
{
    #[Route('/register', name: 'register')]
    public function index(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new Users();
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userPassSubmitted = $user->getPassword();

            $hashedPassword = $passwordHasher->hashPassword(
                $user,
                $userPassSubmitted
            );
            $user->setPassword($hashedPassword);

            $user->setRoles(["ROLE_USER"]);

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('register/index.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
}

templates/register/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}

    {% block header %}{{parent()}}{% endblock %}

    {{ form_start(form)}}
    {% set _block = block('error_message') %}

    {% if _block is not empty %}
    <div class="alert alert-danger text-center">
    {% block error_message %}{{ form_errors(form) }}{{ form_errors(form.password.children['first']) }}{{ form_errors(form.password.children['second']) }}{% endblock %}
    </div>
    {% endif %}

    <h1 class="{% if _block is empty %}mt-5{% endif %}">Inscription</h1>

    <div class="form_container col-xl-3 col-lg-4 col-md-6 col-sm-10 mx-auto mt-3 d-flex flex-column align-items-center" >
        <div class="text-center">
            {{ form_help(form.pseudo) }}{{ form_help(form.email) }}
            <div class="col">
                {{ form_row(form.pseudo, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col">
                {{ form_row(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col">
                {{ form_label(form.password.children['first']) }}
                {{ form_widget(form.password.children['first'], {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col">
                {{ form_label(form.password.children['second']) }}
                {{ form_widget(form.password.children['second'], {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <button class="btn btn-primary mx-auto mt-3">{{ button_label|default('S\'inscrire') }}</button>
    </div>
    {{ form_widget(form._token) }}
    {{ form_end(form, {'render_rest': false}) }}

{% endblock %}